from bot import CMD_INDEX


class _BotCommands:
    def __init__(self):
        self.StartCommand = f'start{CMD_INDEX}'
        self.MirrorCommand = f'directlinkmirror{CMD_INDEX}'
        self.UnzipMirrorCommand = f'unzipdirectlinkmirror{CMD_INDEX}'
        self.ZipMirrorCommand = f'zipdirectlinkmirror{CMD_INDEX}'
        self.CancelMirror = f'cancel{CMD_INDEX}'
        self.CancelAllCommand = f'cancelall{CMD_INDEX}'
        self.ListCommand = f'list{CMD_INDEX}'
        self.SearchCommand = f'search{CMD_INDEX}'
        self.StatusCommand = f'status{CMD_INDEX}'
        self.AuthorizedUsersCommand = f'users{CMD_INDEX}'
        self.AuthorizeCommand = f'authorize{CMD_INDEX}'
        self.UnAuthorizeCommand = f'unauthorize{CMD_INDEX}'
        self.AddSudoCommand = f'addsudo{CMD_INDEX}'
        self.RmSudoCommand = f'rmsudo{CMD_INDEX}'
        self.PingCommand = f'ping{CMD_INDEX}'
        self.RestartCommand = f'restart{CMD_INDEX}'
        self.StatsCommand = f'stats{CMD_INDEX}'
        self.HelpCommand = f'help{CMD_INDEX}'
        self.LogCommand = f'log{CMD_INDEX}'
        self.CloneCommand = f'clone{CMD_INDEX}'
        self.CountCommand = f'count{CMD_INDEX}'
        self.WatchCommand = f'ytdlmirror{CMD_INDEX}'
        self.ZipWatchCommand = f'ytdlzipmirror{CMD_INDEX}'
        self.QbMirrorCommand = f'magnetlinkmirror{CMD_INDEX}'
        self.QbUnzipMirrorCommand = f'unzipmagnetlinkmirror{CMD_INDEX}'
        self.QbZipMirrorCommand = f'zipmagnetlinkmirror{CMD_INDEX}'
        self.DeleteCommand = f'del{CMD_INDEX}'
        self.ShellCommand = f'shell{CMD_INDEX}'
        self.ExecHelpCommand = f'exechelp{CMD_INDEX}'
        self.LeechSetCommand = f'leechset{CMD_INDEX}'
        self.SetThumbCommand = f'setthumb{CMD_INDEX}'
        self.LeechCommand = f'directlinkleech{CMD_INDEX}'
        self.UnzipLeechCommand = f'unzipdirectlinkleech{CMD_INDEX}'
        self.ZipLeechCommand = f'zipdirectlinkleech{CMD_INDEX}'
        self.QbLeechCommand = f'magnetlinkleech{CMD_INDEX}'
        self.QbUnzipLeechCommand = f'unzipmagnetlinkleech{CMD_INDEX}'
        self.QbZipLeechCommand = f'zipmagnetlinkleech{CMD_INDEX}'
        self.LeechWatchCommand = f'ytdlleech{CMD_INDEX}'
        self.LeechZipWatchCommand = f'ytdlzipleech{CMD_INDEX}'
        self.RssListCommand = f'rsslist{CMD_INDEX}'
        self.RssGetCommand = f'rssget{CMD_INDEX}'
        self.RssSubCommand = f'rsssub{CMD_INDEX}'
        self.RssUnSubCommand = f'rssunsub{CMD_INDEX}'
        self.RssSettingsCommand = f'rssset{CMD_INDEX}'

BotCommands = _BotCommands()
